# Generated by Django 4.0.6 on 2024-03-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='quiz_4_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_5_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_6_status',
            field=models.BooleanField(default=False),
        ),
    ]
