# Generated by Django 4.0.6 on 2024-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='start',
            name='name',
            field=models.CharField(default='X', max_length=20),
        ),
    ]
