# Generated by Django 4.0.6 on 2024-04-01 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_team_created_at_team_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 16, 0)),
        ),
    ]
