# Generated by Django 4.0.6 on 2024-04-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_competitionsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionSettings',
        ),
        migrations.DeleteModel(
            name='Start',
        ),
    ]
